### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by thedjpetersen** [hfreire/tinder-wrapper#179]
I realize this may be a bit of a naïve question, but how does one get the access token from facebook? Is there another dependency I need to add to take care of the auth dance?

**Comment by agrublev** [comment]
@thedjpetersen why close with no response?

**Comment by thedjpetersen** [comment]
@agrublev I was able to get it working (I don't remember how though, it was almost 2 years ago)

**Comment by agrublev** [comment]
@thedjpetersen nvm, i ended up making my own react layer on top of the tinder webapp.
![main](https://user-images.githubusercontent.com/801433/88337085-f4d16a80-ccea-11ea-99b9-799f306d655d.png)
got so tired of the clicking around to see all images... took me 15 mins to mimic their api (looking at network tab) and simply injecting a react div on top of the website :D works like a charm!
